# Generated by Django 5.2.7 on 2025-10-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='bank_account_description',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre a conta bancária', verbose_name='Descrição da Conta Bancária'),
        ),
        migrations.AddField(
            model_name='filial',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Ex: Banco do Brasil - Conta Corrente', max_length=200, verbose_name='Nome da Conta Bancária'),
        ),
    ]
