# Generated by Django 5.2.7 on 2025-10-17 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_filial_bank_account_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ da filial', max_length=18, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ do fornecedor', max_length=18, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ'),
        ),
    ]
