# Generated by Django 5.2.7 on 2025-10-17 19:17

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_filial_cnpj_alter_supplier_cnpj'),
        ('tenant', '0002_alter_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filial',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='filial',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ da filial (opcional)', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ do fornecedor (opcional)', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ'),
        ),
        migrations.AddConstraint(
            model_name='filial',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj__isnull', False), models.Q(('cnpj', ''), _negated=True)), fields=('tenant', 'cnpj'), name='unique_filial_cnpj_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj__isnull', False), models.Q(('cnpj', ''), _negated=True)), fields=('tenant', 'cnpj'), name='unique_supplier_cnpj_per_tenant'),
        ),
    ]
