# Generated by Django 5.2.7 on 2025-10-11 03:52

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('slug', models.SlugField(help_text='Identificador único usado nas URLs e headers', max_length=100, unique=True, verbose_name='Identificador')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail Principal')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('cnpj', models.CharField(blank=True, help_text='Formato: 00.000.000/0000-00', max_length=18, verbose_name='CNPJ')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, help_text='Formato: 00000-000', max_length=9, verbose_name='CEP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Logo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='tenant_tena_slug_8b6b77_idx'), models.Index(fields=['cnpj'], name='tenant_tena_cnpj_5e2d1d_idx')],
            },
            bases=(core.models.UppercaseMixin, models.Model),
        ),
    ]
