# Generated by Django 5.2.7 on 2025-10-13 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0001_initial'),
        ('registrations', '0002_filial_bank_account_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payablepayment',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='payablepayment',
            name='paid_by_branch',
            field=models.ForeignKey(blank=True, help_text='Filial que efetivamente realizou o pagamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to='registrations.filial', verbose_name='Pago pela Filial'),
        ),
    ]
