# Generated by Django 5.2.7 on 2025-10-13 23:32

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Objeto')),
                ('file', models.FileField(max_length=500, upload_to=core.models.attachment_upload_path, verbose_name='Arquivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Arquivo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_attach_content_d3cac2_idx'), models.Index(fields=['content_type', 'object_id', 'order'], name='core_attach_content_73905f_idx')],
            },
        ),
    ]
